### ISSUE TITLE
Failed to activate the toolbar-iconshortcuts package

### ISSUE THREAD

**Issue by ohTAZ** [thiagolucio/toolbar-iconshortcuts#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.2 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [toolbar-iconshortcuts](https://github.com/thiagolucio/toolbar-iconshortcuts) package 3.10.0

### Stack Trace

Failed to activate the toolbar-iconshortcuts package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (~/AppData/Local/atom/app-1.14.2/resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at Object.activate (/packages/toolbar-iconshortcuts-master/lib/toolbar-iconshortcuts.coffee:3:5)
  at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
  at /app.asar/src/package.js:190:32
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at /app.asar/src/package.js:183:26
  at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
  at /app.asar/src/package-manager.js:531:29
  at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
  at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
  at /app.asar/src/atom-environment.js:814:28

```

### Commands

```
```

### Non-Core Packages

```
color-picker 2.2.5 
minimap 4.26.8 
tool-bar 1.0.1 
toolbar-iconshortcuts 3.10.0 
tool-bar-main 0.0.10 
```

**Comment by thiagolucio** [comment]
Please, this problem at - https://github.com/atom/atom/issues/8891

The "tool-bar-main 0.0.10" and "toolbar-iconshortcuts 3.10.0" are enable/ active at the same time?Don't used this two tools together.

**Comment by thiagolucio** [comment]
Come here to clarify other problem cause for seti...with you have this theme-ui / theme syntax, please remove that...
https://discuss.atom.io/t/fetching-outdated-packages-and-themes-failed/39539/2
