### ISSUE TITLE
Uncaught TypeError: this.element.querySelector is not a function

### ISSUE THREAD

**Issue by vsoaresbraz** [thiagolucio/toolbar-iconshortcuts#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [toolbar-iconshortcuts](https://github.com/thiagolucio/toolbar-iconshortcuts) package 3.13.0

### Stack Trace

Uncaught TypeError: this.element.querySelector is not a function

```
At C:\Users\Usuario\.atom\packages\toolbar-iconshortcuts\node_modules\atom-package-deps\lib\view.js:41

TypeError: this.element.querySelector is not a function
    at View.advance (/packages/toolbar-iconshortcuts/node_modules/atom-package-deps/lib/view.js:41:36)
    at /packages/toolbar-iconshortcuts/node_modules/atom-package-deps/lib/main.js:53:16
    at stdout (/packages/toolbar-iconshortcuts/node_modules/atom-package-deps/lib/helpers.js:24:11)
    at Socket.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/src/buffered-process.js:219:1)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -6:13.4.0 core:confirm (input.hidden-input)
     -5:33.9.0 core:paste (input.hidden-input)
     -5:33.4.0 core:confirm (input.hidden-input)
     -5:15 core:paste (input.hidden-input)
     -5:13.8.0 core:confirm (input.hidden-input)
     -4:49.2.0 core:paste (input.hidden-input)
     -4:48.5.0 core:confirm (input.hidden-input)
     -4:23.1.0 core:paste (input.hidden-input)
     -4:22.7.0 core:confirm (input.hidden-input)
     -4:13.9.0 core:paste (input.hidden-input)
     -4:12.2.0 core:confirm (input.hidden-input)
     -3:54.5.0 core:paste (input.hidden-input)
  3x -3:54.1.0 core:confirm (input.hidden-input)
     -2:17.1.0 settings-view:open (div.panels-item)
     -2:09.9.0 core:paste (input.hidden-input)
     -2:09.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.26 
atom-bootstrap3 1.2.12 
atom-live-server 2.1.2 
atom-runner 2.7.1 
atom-ternjs 0.18.3 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-java 1.2.7 
autocomplete-modules 1.6.10 
autocomplete-paths 1.0.5 
autoprefixer 3.7.0 
browser-plus 0.0.87 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.10.3 
emmet 2.4.3 
file-icons 2.1.7 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.2 
javascript-snippets 1.2.1 
language-babel 2.65.1 
linter 2.1.4 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-jshint 3.1.2 
linter-ui-default 1.6.0 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
open-in-browser 0.5.2 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
tool-bar 1.1.0 
toolbar-iconshortcuts 3.13.0 
turbo-javascript 1.4.0 
```

**Comment by thiagolucio** [comment]
Did you try to reinstall the package? I have the same environment here but in 3 similar installations simulations, i don't get this error.

**Comment by vsoaresbraz** [comment]
Yes, I reinstalled it and the error disappeared. Thank you!

**Comment by thiagolucio** [comment]
You're welcome!
If you have any one problem with them, please, let me know. I think that problem is caused by a some wrong read file at the moment to install some package dependency from toolbar.  Reinstall in generally solved that problem can you see.  Thanks to feedback again :)
