### ISSUE TITLE
Failed to activate the toolbar-iconshortcuts package

### ISSUE THREAD

**Issue by maroberto** [thiagolucio/toolbar-iconshortcuts#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 20.04
**Thrown From**: [toolbar-iconshortcuts](https://github.com/thiagolucio/toolbar-iconshortcuts) package 3.17.0

### Stack Trace

Failed to activate the toolbar-iconshortcuts package

```
At Cannot find module 'atom-package-deps'
Require stack:
- /home/marcos/.atom/packages/toolbar-iconshortcuts-master/lib/toolbar-iconshortcuts.coffee
- /snap/atom/252/usr/share/atom/resources/app.asar/static/index.html

Error: Cannot find module 'atom-package-deps'
Require stack:
- /home/marcos/.atom/packages/toolbar-iconshortcuts-master/lib/toolbar-iconshortcuts.coffee
- /snap/atom/252/usr/share/atom/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (/snap/atom/252/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:11:146766)
    at Object.activate (/packages/toolbar-iconshortcuts-master/lib/toolbar-iconshortcuts.coffee:3:5)
    at Package.activateNow (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:11:3191965)
    at /snap/atom/252/usr/share/atom/resources/app/static/<embedded>:11:3191377
    at Package.measure (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:11:3188987)
    at /snap/atom/252/usr/share/atom/resources/app/static/<embedded>:11:3191237
    at new Promise (<anonymous>)
    at Package.activate (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:11:3191180)
    at PackageManager.activatePackage (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:11:382738)
    at /snap/atom/252/usr/share/atom/resources/app/static/<embedded>:11:382354
    at Config.transactAsync (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:11:332002)
    at PackageManager.activatePackages (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:11:382304)
    at PackageManager.activate (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:11:381854)
    at /snap/atom/252/usr/share/atom/resources/app/static/<embedded>:1:717578
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:1:718063)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-html-preview 0.2.6 
atom-js-console 1.2.2 
atom-monokai 0.10.9 
atom-ternjs 0.20.0 
autocomplete-java 1.2.7 
basic-java-compile 0.2.5 
best-js-snippets 4.1.0 
emmet 2.4.3 
file-icons 2.1.41 
git-control 0.9.0 
highlight-selected 0.17.0 
hyperclick 0.1.5 
ide-css 0.3.4 
minimap 4.29.9 
monokai-dark 1.5.0 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
todo-show 2.3.2 
tool-bar 1.3.0 
tool-bar-main 0.0.12 
toolbar-iconshortcuts 3.17.0 
```

**Comment by thiagolucio** [comment]
Hi @maroberto 
You need to install the "atom-package-deps" package.
It is not an extension of "Atom Editor" but "npm". Your application needs it. My "toolbar-iconshortcuts" package, is just identifying and returning the problem to you.

Your version of Atom is a "snap" version. You have enabled all security authorities for her. As you are using the latest version of Ubuntu and the Atom Editor in a Snap version this may be causing an exception to access this npm package.

**Comment by thiagolucio** [comment]
@maroberto , desculpe. 
Não percebí que você era Brasileiro. 
Então, você precisa instalar esse pacote aí. Dependência do npm - atom-package-deps. 
Ele poderá ser instalado por este link:
https://www.npmjs.com/package/atom-package-deps 

Não me parece ser um erro do Atom nem da minha extensão. Ela só está te retornando a informação de que precisa deste pacote. Procura também saber se o fato de estar usando a última versão do Ubuntu com o Atom vis Snap está funcionando ok. Pacotes Snap precisam de permissão para acessar certos locais e pastas, pode ser este o problema. 

Outra questão, acho que (porque não me lembro perfeitamente agora) que você está usando a "tool-bar-main" do suda. Acho que se ela estiver ativa dá conflito com a que eu criei.

**Comment by maroberto** [comment]
Olá thiagolucio quero agradecer muito pelo seu contato e suas orientações, vou instalar o pacote recomendado e retirar os que podem causar conflito.
Mais uma vez obrigado, sou novo em programação ainda não tenho muito conhecimento.

**Comment by thiagolucio** [comment]
@maroberto . Imagine irmão. É assim que se aprende mesmo. Qualquer problema me dá um toque no privado que posso ver se lhe ajudo. 
Uma dica daqui do Github com relação a Issues é que quando abrir um ticket que nem fez agora. Ao final sempre feche ele. Eu vou dar close aqui e se perceber alguma coisa errada basta abrir outro.
Grande abraço, tmj :)
